# import pandas as pd
# from sqlalchemy import create_engine

# def validate_data(postgres_uri, raw_table, clean_table, run_id):

#     engine = create_engine(postgres_uri)

#     df = pd.read_sql(
#         f"SELECT * FROM {raw_table} WHERE pipeline_run_id = '{run_id}'",
#         engine
#     )

#     # CLEANING RULES
#     df["base_fare"] = df["base_fare"].abs()
#     df["tax_and_surcharge"] = df["tax_and_surcharge"].fillna(0)

#     df["total_fare"] = df["base_fare"] + df["tax_and_surcharge"]

#     df["validation_status"] = "valid"
#     df["is_peak_season"] = 0
#     df["season_label"] = "Unknown"

#     df.to_sql(clean_table, engine, if_exists="append", index=False)

#     return {"validated_rows": len(df)}

import pandas as pd
from sqlalchemy import create_engine, text

# def validate_data(postgres_uri, raw_table, clean_table, run_id):

#     engine = create_engine(postgres_uri)

#     with engine.connect() as conn:
#         df = pd.read_sql(
#             text(f"SELECT * FROM {raw_table} WHERE pipeline_run_id = :run_id"),
#             conn,
#             params={"run_id": run_id}
#         )

#     # CLEANING RULES
#     df["base_fare"] = df["base_fare"].abs()
#     df["tax_and_surcharge"] = df["tax_and_surcharge"].fillna(0)
#     df["total_fare"] = df["base_fare"] + df["tax_and_surcharge"]

#     df["validation_status"] = "valid"
#     df["is_peak_season"] = 0
#     df["season_label"] = "Unknown"

#     # FIX: 'id' is a SERIAL generated by postgres, not in the DataFrame
#     # Use the DataFrame index as raw_id instead
#     df["raw_id"] = df.index

#     clean_cols = [
#         "raw_id", "airline", "source", "destination",
#         "base_fare", "tax_and_surcharge", "total_fare",
#         "travel_date", "is_peak_season", "season_label",
#         "validation_status", "pipeline_run_id"
#     ]
#     # Only keep columns that actually exist in the dataframe
#     clean_cols = [c for c in clean_cols if c in df.columns or c == "raw_id"]

#     df[clean_cols].to_sql(clean_table, engine, if_exists="append", index=False)

#     return {"validated_rows": len(df)}
def validate_data(mysql_uri, raw_table, clean_table, run_id):
    engine = create_engine(mysql_uri)

    with engine.connect() as conn:
        df = pd.read_sql(
            text(f"SELECT * FROM {raw_table} WHERE pipeline_run_id = :run_id"),
            conn,
            params={"run_id": run_id}
        )

    df["base_fare"] = df["base_fare"].abs()
    df["tax_and_surcharge"] = df["tax_and_surcharge"].fillna(0)
    df["total_fare"] = df["base_fare"] + df["tax_and_surcharge"]
    df["validation_status"] = "valid"
    df["is_peak_season"] = 0
    df["season_label"] = "Unknown"
    df["raw_id"] = df.index

    clean_cols = [
        "raw_id", "airline", "source", "destination",
        "base_fare", "tax_and_surcharge", "total_fare",
        "is_peak_season", "season_label",
        "validation_status", "pipeline_run_id"
    ]
    clean_cols = [c for c in clean_cols if c in df.columns or c == "raw_id"]
    df[clean_cols].to_sql(clean_table, engine, if_exists="append", index=False)

    return {"validated_rows": len(df)}